/**
 * Translate exercise names to Norwegian using a curated dictionary + pattern matching.
 * Sets name_no = Norwegian name, or null if no confident translation exists.
 *
 * Usage: npm run translate:exercises
 */

import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config();

import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { isNull, sql as drizzleSql } from "drizzle-orm";
import * as schema from "../db/schema";

// ---------------------------------------------------------------------------
// Full dictionary — English exercise name → Norwegian
// ---------------------------------------------------------------------------

const DICTIONARY: Record<string, string> = {
  // Core / Mage
  "crunch": "crunch",
  "crunch floor": "crunch på gulvet",
  "crunch (hands overhead)": "crunch (armer over hodet)",
  "crunch (on stability ball)": "crunch på treningsball",
  "crunch (on stability ball, arms straight)": "crunch på treningsball (strake armer)",
  "reverse crunch": "omvendt crunch",
  "cable crunch": "kabel crunch",
  "cable kneeling crunch": "kabel knelende crunch",
  "cable reverse crunch": "kabel omvendt crunch",
  "cable seated crunch": "kabel sittende crunch",
  "cable russian twists (on stability ball)": "kabel russisk vridning på treningsball",
  "bicycle crunch": "sykkelcrunch",
  "cross body crunch": "kroppsvridnings-crunch",
  "oblique crunches floor": "skrå crunch på gulvet",
  "sit-up": "sit-up",
  "sit-up v. 2": "sit-up v. 2",
  "sit-up with arms on chest": "sit-up med armer på brystet",
  "half sit-up (male)": "halv sit-up",
  "quarter sit-up": "kvart sit-up",
  "full sit-up": "full sit-up",
  "jackknife sit-up": "lommekniv sit-up",
  "decline sit-up": "negativ sit-up",
  "decline crunch": "negativ crunch",
  "incline twisting sit-up": "skrå vridnings-sit-up",
  "3/4 sit-up": "3/4 sit-up",
  "russian twist": "russisk vridning",
  "weighted russian twist": "russisk vridning med vekt",
  "plank": "planke",
  "front plank with twist": "planke med vridning",
  "side plank hip adduction": "sideplanke med hofteadduksjon",
  "leg pull in flat bench": "beintrekk på flat benk",
  "lying leg raise flat bench": "liggende beinheving på flat benk",
  "hanging leg raise": "hengende beinheving",
  "hanging straight leg raise": "hengende rett beinheving",
  "hanging knee raise": "hengende knehev",
  "hanging oblique knee raise": "hengende skrå knehev",
  "dead bug": "dead bug",
  "flutter kicks": "flutter spark",
  "mountain climber": "fjellklatrer",
  "tuck crunch": "tuck crunch",
  "v-sit on floor": "v-sete på gulvet",
  "l-sit on floor": "l-sete på gulvet",
  "cocoons": "coconuts",
  "negative crunch": "negativ crunch",
  "knee touch crunch": "kne-touch crunch",
  "frog crunch": "frosk crunch",
  "groin crunch": "lyske crunch",

  // Bryst / Chest
  "barbell bench press": "benkpress med stang",
  "barbell wide bench press": "bred benkpress med stang",
  "barbell incline bench press": "skrå benkpress med stang",
  "barbell decline bench press": "negativ benkpress med stang",
  "barbell close-grip bench press": "smal benkpress med stang",
  "barbell guillotine bench press": "guillotine benkpress",
  "barbell jm bench press": "JM benkpress",
  "barbell incline close grip bench press": "skrå smal benkpress",
  "barbell incline reverse-grip press": "skrå benkpress med omvendt grep",
  "barbell reverse close-grip bench press": "omvendt smal benkpress",
  "barbell reverse grip decline bench press": "omvendt grep negativ benkpress",
  "barbell reverse grip incline bench press": "omvendt grep skrå benkpress",
  "barbell lying close-grip press": "liggende smal press med stang",
  "dumbbell bench press": "benkpress med håndvekt",
  "dumbbell incline bench press": "skrå benkpress med håndvekt",
  "dumbbell decline bench press": "negativ benkpress med håndvekt",
  "dumbbell fly": "brystfly med håndvekt",
  "dumbbell incline fly": "skrå brystfly med håndvekt",
  "dumbbell decline fly": "negativ brystfly med håndvekt",
  "dumbbell pullover": "pullover med håndvekt",
  "cable fly": "kabel brystfly",
  "cable incline fly": "kabel skrå brystfly",
  "cable decline fly": "kabel negativ brystfly",
  "cable cross-over variation": "kabel crossover variant",
  "cable bench press": "kabel benkpress",
  "chest dip": "bryst-dips",
  "push-up": "push-up",
  "close-grip push-up": "smal push-up",
  "wide hand push up": "bred push-up",
  "incline push-up": "skrå push-up",
  "decline push-up": "negativ push-up",
  "diamond push-up": "diamant push-up",
  "clap push up": "klappe push-up",
  "pike-to-cobra push-up": "pike-til-cobra push-up",
  "push-up on lower arms": "push-up på underarmer",
  "push up on bosu ball": "push-up på BOSU-ball",
  "smith bench press": "smith benkpress",
  "smith close-grip bench press": "smith smal benkpress",
  "smith decline bench press": "smith negativ benkpress",
  "smith incline bench press": "smith skrå benkpress",
  "cable upper chest crossovers": "kabel øvre bryst crossover",
  "cable middle fly": "kabel midtre fly",
  "cable low fly": "kabel nedre fly",
  "isometric chest squeeze": "isometrisk brystpress",

  // Rygg / Back
  "barbell deadlift": "markløft med stang",
  "barbell romanian deadlift": "rumensk markløft med stang",
  "barbell stiff leg deadlift": "stivt bein markløft med stang",
  "barbell straight leg deadlift": "rett bein markløft med stang",
  "barbell single leg deadlift": "ett bein markløft med stang",
  "barbell sumo deadlift": "sumo markløft med stang",
  "barbell rack pull": "rack pull med stang",
  "trap bar deadlift": "trapbar markløft",
  "dumbbell deadlift": "markløft med håndvekt",
  "dumbbell romanian deadlift": "rumensk markløft med håndvekt",
  "dumbbell single leg deadlift": "ett bein markløft med håndvekt",
  "dumbbell stiff leg deadlift": "stivt bein markløft med håndvekt",
  "dumbbell straight leg deadlift": "rett bein markløft med håndvekt",
  "cable deadlift": "kabel markløft",
  "smith deadlift": "smith markløft",
  "barbell bent over row": "foroverlent roing med stang",
  "barbell pendlay row": "Pendlay roing",
  "barbell one arm bent over row": "énarms foroverlent roing med stang",
  "barbell reverse grip bent over row": "foroverlent roing med omvendt grep",
  "barbell incline row": "skrå roing med stang",
  "dumbbell bent over row": "foroverlent roing med håndvekt",
  "dumbbell one arm bent-over row": "énarms foroverlent roing med håndvekt",
  "dumbbell incline row": "skrå roing med håndvekt",
  "cable seated row": "kabel sittende roing",
  "cable low seated row": "kabel lav sittende roing",
  "cable straight back seated row": "kabel sittende roing med rett rygg",
  "cable one arm bent over row": "kabel énarms foroverlent roing",
  "cable upper row": "kabel øvre roing",
  "cable rear pulldown": "kabel bakre nedtrekk",
  "pull-up": "pull-up",
  "weighted pull-up": "pull-up med vekt",
  "chin-up": "chins",
  "close grip chin-up": "smal chins",
  "reverse grip pull-up": "omvendt grep pull-up",
  "wide grip pull-up": "bred pull-up",
  "neutral grip pull-up": "nøytralt grep pull-up",
  "pull up (neutral grip)": "pull-up (nøytralt grep)",
  "archer pull up": "bueskytte pull-up",
  "assisted pull-up": "assistert pull-up",
  "cable pulldown": "kabel nedtrekk",
  "cable lat pulldown full range of motion": "kabel lat-nedtrekk fullt bevegelsesutslag",
  "cable lateral pulldown (with rope attachment)": "kabel lateral nedtrekk (med tau)",
  "cable underhand pulldown": "kabel underhånds nedtrekk",
  "cable bar lateral pulldown": "kabel lateral nedtrekk med stang",
  "alternate lateral pulldown": "vekselvis lateral nedtrekk",
  "cable straight arm pulldown": "kabel rett arm nedtrekk",
  "cable straight arm pulldown (with rope)": "kabel rett arm nedtrekk (med tau)",
  "barbell shrug": "skulderheving med stang",
  "dumbbell shrug": "skulderheving med håndvekt",
  "cable shrug": "kabel skulderheving",
  "smith shrug": "smith skulderheving",
  "barbell upright row": "oppreist roing med stang",
  "dumbbell upright row": "oppreist roing med håndvekt",
  "cable upright row": "kabel oppreist roing",
  "smith upright row": "smith oppreist roing",
  "barbell pullover": "pullover med stang",
  "barbell good morning": "god morgen med stang",
  "hyperextension": "ryggekstensjon",
  "hyperextension (on bench)": "ryggekstensjon på benk",
  "back extension on exercise ball": "ryggekstensjon på treningsball",
  "inverted row": "invertert roing",
  "inverted row bent knees": "invertert roing med bøyde knær",
  "suspended row": "hengende roing",
  "rope climb": "taueklatring",
  "lever back extension": "maskin ryggekstensjon",
  "lever bent over row": "maskin foroverlent roing",
  "lever t bar row": "maskin T-bar roing",
  "lever high row": "maskin høy roing",
  "lever narrow grip seated row": "maskin smal sittende roing",
  "lever seated row": "maskin sittende roing",
  "lever front pulldown": "maskin frontnedtrekk",
  "back lever": "bakre lever",
  "front lever": "fremre lever",

  // Skuldre / Shoulders
  "barbell seated overhead press": "sittende skulderpress med stang",
  "barbell standing wide military press": "stående bred militærpress med stang",
  "barbell seated bradford rocky press": "Bradford press",
  "dumbbell shoulder press": "skulderpress med håndvekt",
  "dumbbell seated shoulder press": "sittende skulderpress med håndvekt",
  "dumbbell standing overhead press": "stående skulderpress over hodet",
  "dumbbell one arm shoulder press": "énarms skulderpress med håndvekt",
  "dumbbell arnold press": "Arnold press",
  "dumbbell lateral raise": "sideheving med håndvekt",
  "dumbbell seated lateral raise": "sittende sideheving med håndvekt",
  "dumbbell front raise": "frontløft med håndvekt",
  "dumbbell seated front raise": "sittende frontløft med håndvekt",
  "dumbbell rear delt raise": "bakre skulderheving med håndvekt",
  "dumbbell rear lateral raise": "bakre lateral heving med håndvekt",
  "dumbbell incline rear lateral raise": "skrå bakre lateral heving med håndvekt",
  "cable lateral raise": "kabel sideheving",
  "cable one arm lateral raise": "kabel énarms sideheving",
  "cable front raise": "kabel frontløft",
  "cable forward raise": "kabel fremover heving",
  "cable rear delt row (with rope)": "kabel bakre skulder roing (med tau)",
  "cable shoulder press": "kabel skulderpress",
  "cable seated rear lateral raise": "kabel sittende bakre lateral heving",
  "landmine lateral raise": "landmine sideheving",
  "smith seated shoulder press": "smith sittende skulderpress",
  "smith standing military press": "smith stående militærpress",
  "lever shoulder press": "maskin skulderpress",
  "lever lateral raise": "maskin sideheving",
  "lever seated fly": "maskin sittende fly",
  "lever seated reverse fly": "maskin sittende bakre fly",
  "face pull": "face pull",
  "cable face pull": "kabel face pull",

  // Biceps
  "barbell curl": "bicepscurl med stang",
  "barbell standing wide grip biceps curl": "bred bicepscurl stående med stang",
  "barbell preacher curl": "predikantcurl med stang",
  "barbell reverse curl": "omvendt curl med stang",
  "barbell drag curl": "drag curl med stang",
  "barbell prone incline curl": "skrå liggende curl med stang",
  "dumbbell biceps curl": "bicepscurl med håndvekt",
  "dumbbell hammer curl": "hammergrep curl med håndvekt",
  "dumbbell concentration curl": "konsentrasjonskurl med håndvekt",
  "dumbbell preacher curl": "predikantcurl med håndvekt",
  "dumbbell alternate biceps curl": "vekselvis bicepscurl med håndvekt",
  "dumbbell seated bicep curl": "sittende bicepscurl med håndvekt",
  "dumbbell standing biceps curl": "stående bicepscurl med håndvekt",
  "dumbbell reverse preacher curl": "omvendt predikantcurl med håndvekt",
  "dumbbell zottman curl": "Zottman curl",
  "dumbbell waiter biceps curl": "kelner bicepscurl",
  "dumbbell incline biceps curl": "skrå bicepscurl med håndvekt",
  "dumbbell incline hammer curl": "skrå hammergrep curl med håndvekt",
  "dumbbell cross body hammer curl": "kroppsvridnings hammergrep curl",
  "cable curl": "kabel curl",
  "cable concentration curl": "kabel konsentrasjonskurl",
  "cable overhead curl": "kabel overhead curl",
  "cable hammer curl (with rope)": "kabel hammergrep curl (med tau)",
  "cable close grip curl": "kabel smalt grep curl",
  "cable one arm curl": "kabel énarms curl",
  "cable reverse curl": "kabel omvendt curl",
  "cable preacher curl": "kabel predikantcurl",
  "cable drag curl": "kabel drag curl",
  "cable squatting curl": "kabel knebøy curl",
  "band alternating biceps curl": "strikk vekselvis bicepscurl",
  "band concentration curl": "strikk konsentrasjonskurl",
  "lever bicep curl": "maskin bicepscurl",
  "lever preacher curl": "maskin predikantcurl",
  "lever hammer grip preacher curl": "maskin hammergrep predikantcurl",
  "ez barbell curl": "EZ-stang curl",
  "ez barbell close-grip curl": "EZ-stang smal curl",
  "ez barbell reverse grip curl": "EZ-stang omvendt grep curl",
  "ez barbell reverse grip preacher curl": "EZ-stang omvendt predikantcurl",
  "ez barbell seated curls": "EZ-stang sittende curl",

  // Triceps
  "barbell lying triceps extension": "liggende tricepsstrekk med stang",
  "barbell lying close-grip triceps extension": "liggende smal tricepsstrekk med stang",
  "barbell lying triceps extension skull crusher": "skull crusher med stang",
  "barbell seated close grip behind neck triceps extension": "sittende tricepsstrekk bak nakken",
  "barbell standing overhead triceps extension": "stående tricepsstrekk over hodet",
  "dumbbell lying triceps extension": "liggende tricepsstrekk med håndvekt",
  "dumbbell one arm triceps extension (on bench)": "énarms tricepsstrekk på benk",
  "dumbbell seated triceps extension": "sittende tricepsstrekk med håndvekt",
  "dumbbell tricep kickback with stork stance": "triceps kickback med håndvekt",
  "dumbbell kickback": "kickback med håndvekt",
  "cable pushdown": "kabel nedpress",
  "cable pushdown (with rope attachment)": "kabel nedpress (med tau)",
  "cable triceps pushdown (v-bar)": "kabel triceps nedpress (V-stang)",
  "cable rope high pulley overhead tricep extension": "kabel tau overhead tricepsstrekk",
  "cable overhead triceps extension (rope attachment)": "kabel overhead tricepsstrekk (tau)",
  "cable incline triceps extension": "kabel skrå tricepsstrekk",
  "cable kneeling triceps extension": "kabel knelende tricepsstrekk",
  "cable alternate triceps extension": "kabel vekselvis tricepsstrekk",
  "cable standing one arm triceps extension": "kabel stående énarms tricepsstrekk",
  "cable two arm tricep kickback": "kabel toarms triceps kickback",
  "triceps dip": "triceps-dips",
  "bench dip (knees bent)": "benkdips (bøyde knær)",
  "dip": "dips",
  "chest dip (on dip-pull-up cage)": "brystdips på dips-stativ",
  "band side triceps extension": "strikk sidestrekk triceps",
  "lever overhand triceps dip": "maskin triceps-dips",
  "lever triceps extension": "maskin tricepsstrekk",
  "ez bar french press on exercise ball": "EZ-stang French press på treningsball",
  "ez barbell seated triceps extension": "EZ-stang sittende tricepsstrekk",
  "ez barbell decline triceps extension": "EZ-stang negativ tricepsstrekk",
  "ez barbell incline triceps extension": "EZ-stang skrå tricepsstrekk",
  "skull crusher": "skull crusher",
  "bodyweight kneeling triceps extension": "knelende tricepsstrekk med kroppsvekt",

  // Ben / Legs
  "barbell squat": "knebøy med stang",
  "barbell full squat": "fullt knebøy med stang",
  "barbell front squat": "frontknebøy med stang",
  "barbell hack squat": "hack squat med stang",
  "barbell sumo deadlift": "sumo markløft med stang",
  "barbell lunge": "utfall med stang",
  "barbell rear lunge": "bakre utfall med stang",
  "barbell lateral lunge": "sideutfall med stang",
  "barbell side split squat": "side splittknebøy med stang",
  "barbell single leg split squat": "ettbein splittknebøy med stang",
  "barbell jump squat": "hopp-knebøy med stang",
  "barbell high bar squat": "høy stang knebøy",
  "barbell low bar squat": "lav stang knebøy",
  "barbell overhead squat": "overhead knebøy",
  "barbell zercher squat": "Zercher knebøy",
  "barbell jefferson squat": "Jefferson knebøy",
  "barbell speed squat": "tempo-knebøy med stang",
  "barbell wide squat": "bred knebøy med stang",
  "barbell step-up": "step-up med stang",
  "dumbbell squat": "knebøy med håndvekt",
  "dumbbell goblet squat": "goblet knebøy",
  "dumbbell lunge": "utfall med håndvekt",
  "dumbbell rear lunge": "bakre utfall med håndvekt",
  "dumbbell step-up": "step-up med håndvekt",
  "dumbbell single leg squat": "ettbein knebøy med håndvekt",
  "dumbbell single leg split squat": "ettbein splittknebøy med håndvekt",
  "dumbbell sumo pull through": "sumo pull-through med håndvekt",
  "dumbbell plyo squat": "plyometrisk knebøy med håndvekt",
  "kettlebell goblet squat": "goblet knebøy med kettlebell",
  "kettlebell front squat": "frontknebøy med kettlebell",
  "kettlebell pistol squat": "pistol-knebøy med kettlebell",
  "kettlebell swing": "kettlebell swing",
  "kettlebell sumo high pull": "sumo høytrekk med kettlebell",
  "kettlebell thruster": "kettlebell thruster",
  "walking lunge": "gående utfall",
  "lunge with jump": "hopputfall",
  "lunge with twist": "utfall med vridning",
  "curtsey squat": "høflighetsknebøy",
  "sissy squat": "sissy knebøy",
  "split squats": "splittknebøy",
  "jump squat": "hoppknebøy",
  "squat on bosu ball": "knebøy på BOSU-ball",
  "potty squat": "dyphukk",
  "frankenstein squat": "Frankenstein knebøy",
  "squat jerk": "knebøy-støt",
  "one leg squat": "ettbeins knebøy",
  "single leg squat (pistol) male": "pistol-knebøy",
  "suspended split squat": "hengende splittknebøy",
  "lever leg extension": "maskin benstrekk",
  "lever lying leg curl": "maskin liggende beincurl",
  "lever seated leg curl": "maskin sittende beincurl",
  "lever kneeling leg curl": "maskin knelende beincurl",
  "lever seated leg raise crunch": "maskin sittende beinheving",
  "sled 45в° leg press": "beinpress 45 grader",
  "sled 45° leg press (side pov)": "beinpress 45 grader",
  "sled 45в° calf press": "legpress tåhev",
  "sled hack squat": "sled hack squat",
  "dumbbell step-up lunge": "step-up utfall med håndvekt",
  "walking high knees lunge": "gående høyknær utfall",
  "box jump down with one leg stabilization": "boksehopp ned med ettbein stabilisering",
  "kneeling jump squat": "knelende hoppknebøy",
  "leg pull in flat bench": "beintrekk på flat benk",
  "lever alternating narrow grip seated row": "maskin vekselvis sittende roing",
  "smith squat": "smith knebøy",
  "smith front squat (clean grip)": "smith frontknebøy",
  "smith full squat": "smith fullt knebøy",
  "smith hack squat": "smith hack squat",
  "smith sumo squat": "smith sumo knebøy",
  "smith leg press": "smith beinpress",
  "smith single leg split squat": "smith ettbein splittknebøy",
  "smith sprint lunge": "smith sprint utfall",
  "lever hip extension v. 2": "maskin hofteekstensjon",
  "lever horizontal one leg press": "maskin horisontal ettbein press",
  "lever seated squat calf raise on leg press machine": "maskin sittende knebøy tåhev",
  "reverse hyper extension (on stability ball)": "omvendt ryggekstensjon på treningsball",

  // Legger / Calves
  "barbell standing calf raise": "stående tåhev med stang",
  "barbell seated calf raise": "sittende tåhev med stang",
  "dumbbell standing calf raise": "stående tåhev med håndvekt",
  "dumbbell single leg calf raise": "ettbeins tåhev med håndvekt",
  "dumbbell seated calf raise": "sittende tåhev med håndvekt",
  "single leg calf raise (on a dumbbell)": "ettbeins tåhev på håndvekt",
  "donkey calf raise": "esel tåhev",
  "weighted donkey calf raise": "esel tåhev med vekt",
  "standing calf raise (on a staircase)": "stående tåhev på trapp",
  "standing calves": "stående tåhev",
  "bodyweight standing calf raise": "stående tåhev med kroppsvekt",
  "hack calf raise": "hack tåhev",
  "lever standing calf raise": "maskin stående tåhev",
  "lever seated calf raise": "maskin sittende tåhev",
  "lever calf press": "maskin legpress tåhev",
  "lever donkey calf raise": "maskin esel tåhev",
  "sled calf press on leg press": "sled tåhev på beinpress",
  "sled 45в° leg wide press": "bred sled beinpress 45 grader",
  "lever rotary calf": "maskin roterende tåhev",
  "smith standing leg calf raise": "smith stående tåhev",
  "one leg floor calf raise": "ettbeins tåhev på gulvet",
  "one leg donkey calf raise": "ettbeins esel tåhev",
  "band single leg calf raise": "strikk ettbeins tåhev",
  "cable standing calf raise": "kabel stående tåhev",
  "cable standing one leg calf raise": "kabel stående ettbeins tåhev",
  "calf push stretch with hands against wall": "leggstrekk mot vegg",
  "calf stretch with rope": "leggstrekk med tau",

  // Rumpe / Glutes
  "barbell glute bridge": "rumpeløft med stang",
  "barbell hip thrust": "hoftepress med stang",
  "glute bridge march": "rumpeløft med march",
  "glute bridge two legs on bench (male)": "rumpeløft med bein på benk",
  "glute-ham raise": "glute-ham heving",
  "hip raise (bent knee)": "hofteheving (bøyde knær)",
  "low glute bridge on floor": "lav rumpeløft på gulvet",
  "single leg bridge with outstretched leg": "ettbeins bru med utstrakt bein",
  "pelvic tilt into bridge": "bekkentilt til bru",
  "cable standing hip extension": "kabel stående hofteekstensjon",
  "cable hip adduction": "kabel hofteadduksjon",
  "band bent-over hip extension": "strikk foroverlent hofteekstensjon",
  "band hip lift": "strikk hofteløft",
  "resistance band hip thrusts on knees (female)": "strikk hoftepress på knær",
  "lever seated hip abduction": "maskin sittende hofteabduksjon",
  "lever seated hip adduction": "maskin sittende hofteadduksjon",
  "lever reverse hyperextension": "maskin omvendt ryggekstensjon",
  "side hip abduction": "sidehofteabduksjon",
  "monster walk": "monster gange",
  "donkey kick": "eselspill",

  // Hofter / Hips
  "cable pull through (with rope)": "kabel pull-through (med tau)",
  "barbell hip thrust": "hoftepress med stang",
  "kettlebell turkish get up (squat style)": "tyrkisk reisning med kettlebell",
  "landmine 180": "landmine 180",

  // Skuldre / Traps
  "barbell shrug": "skulderheving med stang",
  "dumbbell shrug": "skulderheving med håndvekt",
  "cable shrug": "kabel skulderheving",
  "kettlebell alternating hang clean": "vekselvis hengende støt med kettlebell",

  // Cardio / Kondisjon
  "run": "løp",
  "burpee": "burpee",
  "jump rope": "hoppetau",
  "mountain climber": "fjellklatrer",
  "air bike": "luftsykkel",
  "jack jump (male)": "stjernehopphopp",
  "star jump (male)": "stjernhopp",
  "skater hops": "skøytesprang",
  "scissor jumps (male)": "saksehopp",
  "forward jump": "fremoverhopp",
  "backward jump": "bakoverhopp",
  "box jump down with one leg stabilization": "boksehopp ned",
  "astride jumps (male)": "spredehopp",
  "high knee against wall": "høyt kne mot vegg",
  "battling ropes": "battle ropes",
  "athletic style battling ropes": "battle ropes atletisk stil",
  "stationary bike run": "stasjonær sykkel",
  "stationary bike walk": "stasjonær sykkel (rolig)",
  "walk elliptical cross trainer": "ellipsemaskin",
  "walking on incline treadmill": "gange på skrå tredemølle",
  "walking on stepmill": "trappemølle",
  "ski ergometer": "skiergometer",
  "tire flip": "dekkvending",
  "sledge hammer": "sleggehammer",

  // Strukk / Stretching
  "hamstring stretch": "hamstringstrekk",
  "seated calf stretch (male)": "sittende leggstrekk",
  "runners stretch": "løperstrekk",
  "world greatest stretch": "verdens beste strekk",
  "chest and front of shoulder stretch": "bryst- og skulderstrekning",
  "rear deltoid stretch": "bakre skulderstrekning",
  "upper back stretch": "øvre ryggsstrekning",
  "seated lower back stretch": "sittende nedre ryggsstrekning",
  "seated glute stretch": "sittende rumpestrekning",
  "overhead triceps stretch": "tricepsstrekning over hodet",
  "neck side stretch": "nakkestrekk til siden",
  "iron cross stretch": "jernkors-strekk",
  "standing lateral stretch": "stående sidestrekk",
  "spine stretch": "ryggsøylestrekk",
  "butterfly yoga pose": "sommerfuglpose",
  "kneeling lat stretch": "knelende breddestrekk",
  "lying (side) quads stretch": "liggende (side) lårstrekning",
  "leg up hamstring stretch": "hamstringstrekk med bein opp",
  "ankle circles": "ankelrotasjoner",
  "wrist circles": "håndleddsrotasjoner",
  "hip raise (bent knee)": "hofteheving (bøyde knær)",

  // Funksjonelle / Functional
  "kettlebell swing": "kettlebell swing",
  "kettlebell turkish get up (squat style)": "tyrkisk reisning",
  "power clean": "kraftstøt",
  "snatch pull": "rykk-trekk",
  "trap bar deadlift": "trapbar markløft",
  "farmers walk": "farmers walk",
  "inchworm": "inchorm",
  "bear crawl": "bjørnekrabling",
  "alternating bear crawl": "vekselvis bjørnekrabling",
  "crab twist toe touch": "krabbe-vridning tåtouch",
  "handstand": "håndstand",
  "handstand push-up": "håndstand push-up",
  "muscle up": "muscle up",
  "kipping muscle up": "kipping muscle up",
  "back pec stretch": "bryst- og ryggsstrekning",
  "scapula push-up": "skulderblad push-up",
  "scapular pull-up": "skulderblad pull-up",
  "skin the cat": "skin the cat",
  "ring dips": "ring-dips",
  "rope climb": "tauklatring",
  "spin around": "rotasjonsøvelse",

  // Magemuskulatur / Core
  "dead bug": "dead bug",
  "bird dog": "fuglehund",
  "plank": "planke",
  "side plank": "sideplanke",
  "swiss ball crunch": "treningsball crunch",
  "ab wheel rollout": "magehjulsutrulling",
  "standing wheel rollerout": "stående magehjulsutrulling",
  "roller body saw": "rullende body saw",
  "pelvic tilt": "bekkentilt",
  "seated leg raise": "sittende beinheving",
  "captain's chair leg raise": "kapteinsstolen beinheving",

  // Underarm / Forearms
  "barbell wrist curl": "håndledds-curl med stang",
  "barbell palms down wrist curl over a bench": "håndledds-curl med stang, håndflate ned",
  "barbell palms up wrist curl over a bench": "håndledds-curl med stang, håndflate opp",
  "barbell reverse wrist curl": "omvendt håndledds-curl med stang",
  "dumbbell wrist curl": "håndledds-curl med håndvekt",
  "dumbbell reverse wrist curl": "omvendt håndledds-curl med håndvekt",
  "cable wrist curl": "kabel håndledds-curl",
  "cable reverse wrist curl": "kabel omvendt håndledds-curl",
  "finger curls": "fingercurl",
  "dumbbell finger curls": "fingercurl med håndvekt",
  "wrist rollerer": "håndleddsruller",

  // Diverse
  "balance board": "balanseplate",
  "medicine ball overhead slam": "medisinball overhead slam",
  "medicine ball chest pass": "medisinball brystpasning",
  "medicine ball close grip push up": "medisinball smal push-up",
  "battle ropes": "battle ropes",
  "jump squat": "hoppknebøy",
  "dumbbell push press": "push press med håndvekt",
  "barbell thruster": "thruster med stang",
  "barbell clean and press": "støt og press med stang",
  "barbell one arm snatch": "énarms rykk med stang",
  "kettlebell one arm snatch": "énarms rykk med kettlebell",
  "kettlebell double snatch": "dobbelt rykk med kettlebell",
  "dumbbell one arm snatch": "énarms rykk med håndvekt",
  "spell caster": "spell caster",
  "cable twist": "kabel-vridning",
  "cable seated twist": "kabel sittende vridning",
  "barbell standing twist": "stående vridning med stang",
  "cable side bend": "kabel sidebøy",
  "dumbbell side bend": "sidebøy med håndvekt",
  "dumbbell standing alternate raise": "stående vekselvis heving med håndvekt",
  "upper back stretch": "øvre ryggsstrekning",
  "seated wide angle pose sequence": "sittende benvinklet strekk",
  "shoulder tap": "skulder-tap",
  "shoulder tap push-up": "skulder-tap push-up",
  "elbow dips": "albu-dips",
  "elbow-to-knee": "albu-til-kne",
  "band squat": "strikk knebøy",
  "band squat row": "strikk knebøy-roing",
  "band shoulder press": "strikk skulderpress",
  "band front raise": "strikk frontløft",
  "band lateral raise": "strikk sideheving",
  "band bench press": "strikk benkpress",
  "band assisted pull-up": "strikk-assistert pull-up",
  "band pull through": "strikk pull-through",
  "band stiff leg deadlift": "strikk stivt bein markløft",
  "band squat": "strikk knebøy",
  "resistance band seated biceps curl": "sittende bicepscurl med strikk",
  "resistance band seated chest press": "sittende brystpress med strikk",
  "resistance band seated shoulder press": "sittende skulderpress med strikk",
  "resistance band leg extension": "benstrekk med strikk",
  "smith chair squat": "smith stol-knebøy",
  "smith bent knee good morning": "smith god morgen med bøyde knær",
  "smith bent over row": "smith foroverlent roing",
  "smith incline shoulder raises": "smith skrå skulderheving",
  "smith hip raise": "smith hofteheving",
  "smith low bar squat": "smith lav stang knebøy",
  "smith narrow row": "smith smal roing",
  "smith one arm row": "smith énarms roing",
  "smith behind neck press": "smith nakkepress",
  "smith back shrug": "smith bakre skulderheving",
  "smith reverse grip bent over row": "smith omvendt grip foroverlent roing",
  "smith reverse-grip press": "smith omvendt grep press",
  "smith toe raise": "smith tåheving",
  "suspended abdominal fallout": "hengende mage-fallout",
  "suspended push-up": "hengende push-up",
  "suspended split squat": "hengende splittknebøy",
  "suspended reverse crunch": "hengende omvendt crunch",
  "glute-ham raise": "glute-ham heving",
  "nordic hamstring": "nordisk hamstringcurl",
  "inverse leg curl (bench support)": "omvendt beincurl (benkstøtte)",
  "self assisted inverse leg curl": "selvhjulpen omvendt beincurl",
  "lever lying two-one leg curl": "maskin liggende ettbein curl",
  "lever kneeling twist": "maskin knelende vridning",
  "lever seated good morning": "maskin sittende god morgen",
  "lever seated calf press": "maskin sittende legpress tåhev",
  "lever seated crunch": "maskin sittende crunch",
  "lever seated dip": "maskin sittende dips",
  "lever shrug": "maskin skulderheving",
  "lever gripless shrug": "maskin skulderheving (uten grep)",
  "lever pullover": "maskin pullover",
  "lever reverse grip lateral pulldown": "maskin omvendt grep lateral nedtrekk",
  "lever military press": "maskin militærpress",
  "lever chest press": "maskin brystpress",
  "lever incline chest press": "maskin skrå brystpress",
  "lever decline chest press": "maskin negativ brystpress",
  "kettlebell two arm military press": "kettlebell toarms militærpress",
  "kettlebell seated press": "sittende kettlebell press",
  "kettlebell one arm military press to the side": "ettarms kettlebell militærpress til siden",
  "kettlebell one arm push press": "ettarms kettlebell push press",
  "kettlebell one arm clean and jerk": "ettarms kettlebell støt og jerk",
  "kettlebell one arm row": "ettarms kettlebell roing",
  "kettlebell alternating row": "vekselvis kettlebell roing",
  "kettlebell alternating press": "vekselvis kettlebell press",
  "kettlebell two arm row": "toarms kettlebell roing",
  "kettlebell windmill": "kettlebell vindmølle",
  "kettlebell advanced windmill": "avansert kettlebell vindmølle",
  "kettlebell hang clean": "kettlebell hengende støt",
  "kettlebell front squat": "kettlebell frontknebøy",
  "kettlebell lunge pass through": "kettlebell utfall med passering",
  "kettlebell figure 8": "kettlebell figur 8",
  "kettlebell plyo push-up": "kettlebell plyometrisk push-up",
  "cable seated one arm alternate row": "kabel sittende vekselvis énarms roing",
  "cable rope seated row": "kabel tau sittende roing",
  "cable seated wide-grip row": "kabel sittende bred roing",
  "cable lateral pulldown (with rope attachment) core": "kabel lateral nedtrekk (med tau)",
  "cable rope extension incline bench row": "kabel tau skrå benk roing",
  "cable rope hammer preacher curl": "kabel tau hammergrep predikantcurl",
  "cable one arm pulldown": "kabel énarms nedtrekk",
  "cable one arm incline press": "kabel énarms skrå press",
  "cable one arm decline chest fly": "kabel énarms negativ brystfly",
  "cable one arm incline fly on exercise ball": "kabel énarms skrå fly på treningsball",
  "cable squat row (with rope attachment)": "kabel knebøy-roing (med tau)",
  "cable hip adduction": "kabel hofteadduksjon",
  "cable kneeling rear delt row (with rope) (male)": "kabel knelende bakre skulder roing",
  "cable standing rear delt row (with rope)": "kabel stående bakre skulder roing",
  "cable high row (kneeling)": "kabel høy roing (knelende)",
  "cable judo flip": "kabel judo-vending",
  "cable russian twists (on stability ball)": "kabel russisk vridning på treningsball",
  "cable incline pushdown": "kabel skrå nedpress",
  "cable incline bench press": "kabel skrå benkpress",
  "cable incline bench row": "kabel skrå benk roing",
  "cable low fly": "kabel lav fly",
  "cable middle fly": "kabel midtre fly",
  "cable upper chest crossovers": "kabel øvre bryst crossover",
  "cable standing fly": "kabel stående fly",
  "cable standing twist row (v-bar)": "kabel stående vridnings-roing (V-stang)",
  "cable standing shoulder external rotation": "kabel stående ytre skulderrotasjon",
  "cable seated shoulder internal rotation": "kabel sittende indre skulderrotasjon",
  "cable rear pulldown": "kabel bakre nedtrekk",
  "cable cross-over revers fly": "kabel crossover bakre fly",
  "cable tuck reverse crunch": "kabel tuck omvendt crunch",
  "cable lying bicep curl": "kabel liggende bicepscurl",
  "cable lying close-grip curl": "kabel liggende smal curl",
  "cable lying extension pullover (with rope attachment)": "kabel liggende strekk-pullover",
  "cable lying fly": "kabel liggende fly",
  "cable lying triceps extension v. 2": "kabel liggende tricepsstrekk",
  "cable supine reverse fly": "kabel liggende bakre fly",
  "cable standing crunch": "kabel stående crunch",
  "cable standing crunch (with rope attachment)": "kabel stående crunch (med tau)",
  "cable standing lift": "kabel stående løft",
  "cable standing pulldown (with rope)": "kabel stående nedtrekk (med tau)",
  "cable standing up straight crossovers": "kabel stående crossover",
  "cable standing back wrist curl": "kabel stående bakre håndledds-curl",
  "cable seated chest press": "kabel sittende brystpress",
  "cable seated curl": "kabel sittende curl",
  "cable seated high row (v-bar)": "kabel sittende høy roing (V-stang)",
  "cable seated overhead curl": "kabel sittende overhead curl",
  "cable seated twist": "kabel sittende vridning",
  "cable seated row with reverse": "kabel sittende roing med omvendt grep",
  "cable seated wide-grip row": "kabel sittende bred roing",
  "cable two arm curl on incline bench": "kabel toarms curl på skrå benk",
  "cable high pulley overhead tricep extension": "kabel høy overhead tricepsstrekk",
  "cable triceps pushdown (v-bar) (with arm blaster)": "kabel triceps nedpress (V-stang)",
  "cable standing one leg calf raise": "kabel stående ettbeins tåhev",
  "cable thibaudeau kayak row": "kabel kajakkroing",
  "cable twisting pull": "kabel vridningstrekk",
  "cable vertical pallof press": "kabel vertikal pallof press",
  "cable horizontal pallof press": "kabel horisontal pallof press",
  "cable assisted inverse leg curl": "kabel assistert omvendt beincurl",
  "cable forward raise": "kabel fremover heving",
  "cable kickback": "kabel kickback",
  "cable judo flip": "kabel judo-vending",
  "cable press on exercise ball": "kabel press på treningsball",
  "cable reverse crunch": "kabel omvendt crunch",
  "cable reverse curl": "kabel omvendt curl",
  "cable reverse grip triceps pushdown (sz-bar) (with arm blaster)": "kabel omvendt grip triceps nedpress",
  "cable reverse one arm curl": "kabel omvendt énarms curl",
  "cable reverse preacher curl": "kabel omvendt predikantcurl",
  "cable reverse wrist curl": "kabel omvendt håndledds-curl",
  "cable palm rotational row": "kabel roterende roing",
  "cable high pulley overhead tricep extension": "kabel overhead tricepsstrekk",
  "cable pulldown bicep curl": "kabel nedtrekk bicepscurl",
  "cable pulldown (pro lat bar)": "kabel nedtrekk (pro lat stang)",
  "cable lat pulldown full range of motion": "kabel lat-nedtrekk fullt bevegelsesutslag",
  "cable drag curl": "kabel drag curl",
  "cable concentration extension (on knee)": "kabel konsentrasjonsstrekk (på kne)",
  "cable close grip curl": "kabel smal curl",
  "cable bar lateral pulldown": "kabel lateral nedtrekk",
  "cable decline fly": "kabel negativ fly",
  "cable decline seated wide-grip row": "kabel sittende bred negativ roing",
  "cable decline press": "kabel negativ press",
  "cable decline one arm press": "kabel negativ énarms press",
  "cable floor seated wide-grip row": "kabel gulvsittende bred roing",
  "cable incline fly (on stability ball)": "kabel skrå fly på treningsball",
  "cable incline bench row - elite variation": "kabel skrå benk roing - avansert",
  "cable low seated row controlled": "kabel lav sittende roing (kontrollert)",
  "cable straight back seated row": "kabel rett rygg sittende roing",
  "cable rear delt row (stirrups)": "kabel bakre skulder roing (støtter)",
  "cable rear drive": "kabel bakre drive",
  "cable standing cross-over high reverse fly": "kabel stående crossover høy bakre fly",
  "cable rope crossover seated row": "kabel tau crossover sittende roing",
  "cable rope elevated seated row": "kabel tau forhøyet sittende roing",
  "cable wide grip rear pulldown behind neck": "kabel bred nakke-nedtrekk",
  "cable alternate shoulder press": "kabel vekselvis skulderpress",
  "cable shoulder press": "kabel skulderpress",
  "cable squat row (with rope attachment) heavy": "kabel knebøy-roing (tungt)",
  "cable squatting curl": "kabel knebøy-curl",
  "cable cross-over lateral pulldown": "kabel crossover lateral nedtrekk",
  "cable standing inner curl": "kabel stående indre curl",
  "cable standing row (v-bar)": "kabel stående roing (V-stang)",
  "cable overhead curl on exercise ball": "kabel overhead curl på treningsball",
  "cable overhead curl": "kabel overhead curl",
  "cable upper row": "kabel øvre roing",
  "cable reverse-grip pushdown": "kabel omvendt grep nedpress",
  "cable reverse-grip straight back seated high row": "kabel omvendt grep rett rygg høy roing",
  "cable one arm straight back high row (kneeling)": "kabel énarms høy roing (knelende)",
  "cable one arm preacher curl": "kabel énarms predikantcurl",
  "cable one arm reverse preacher curl": "kabel énarms omvendt predikantcurl",
  "cable one arm tricep pushdown": "kabel énarms triceps nedpress",
  "cable one arm fly on exercise ball": "kabel énarms fly på treningsball",
  "cable one arm press on exercise ball": "kabel énarms press på treningsball",
  "cable one arm incline press on exercise ball": "kabel énarms skrå press på treningsball",
  "cable one arm incline press with rigid": "kabel énarms skrå press",
  "cable one arm lateral bent-over": "kabel énarms foroverlent sideheving",
  "dumbbell alternate side press": "vekselvis sidepress med håndvekt",
  "dumbbell seated alternate front raise": "sittende vekselvis frontløft med håndvekt",
  "dumbbell seated alternate hammer curl on exercise ball": "sittende vekselvis hammergrep curl på treningsball",
  "dumbbell seated alternate press": "sittende vekselvis press med håndvekt",
  "dumbbell biceps curl reverse": "omvendt bicepscurl med håndvekt",
  "dumbbell clean": "støt med håndvekt",
  "dumbbell close grip press": "smal press med håndvekt",
  "dumbbell concentration curl": "konsentrasjonskurl med håndvekt",
  "dumbbell contralateral forward lunge": "kontralateralt fremover utfall med håndvekt",
  "dumbbell cuban press": "cubansk press med håndvekt",
  "dumbbell fly on exercise ball": "brystfly på treningsball",
  "dumbbell goblet squat": "goblet knebøy med håndvekt",
  "dumbbell incline alternate press": "skrå vekselvis press med håndvekt",
  "dumbbell incline breeding": "skrå brystøvelse med håndvekt",
  "dumbbell incline curl": "skrå curl med håndvekt",
  "dumbbell incline fly on exercise ball": "skrå fly på treningsball",
  "dumbbell incline hammer press": "skrå hammergrep press med håndvekt",
  "dumbbell incline inner biceps curl": "skrå indre bicepscurl med håndvekt",
  "dumbbell incline one arm fly": "skrå énarms fly med håndvekt",
  "dumbbell incline one arm hammer press": "skrå énarms hammergrep press",
  "dumbbell incline one arm lateral raise": "skrå énarms sideheving med håndvekt",
  "dumbbell incline one arm press": "skrå énarms press med håndvekt",
  "dumbbell incline raise": "skrå heving med håndvekt",
  "dumbbell incline shrug": "skrå skulderheving med håndvekt",
  "dumbbell incline t-raise": "skrå T-heving med håndvekt",
  "dumbbell incline triceps extension": "skrå tricepsstrekk med håndvekt",
  "dumbbell incline y-raise": "skrå Y-heving med håndvekt",
  "dumbbell iron cross": "jernkors med håndvekt",
  "dumbbell lateral to front raise": "sideheving til frontløft med håndvekt",
  "dumbbell lunge with bicep curl": "utfall med bicepscurl med håndvekt",
  "dumbbell lying alternate extension": "liggende vekselvis strekk med håndvekt",
  "dumbbell lying elbow press": "liggende albu-press med håndvekt",
  "dumbbell lying external shoulder rotation": "liggende ytre skulderrotasjon med håndvekt",
  "dumbbell lying femoral": "liggende lårstrekk med håndvekt",
  "dumbbell lying hammer press": "liggende hammergrep press med håndvekt",
  "dumbbell lying on floor rear delt raise": "liggende bakre skulderheving på gulvet",
  "dumbbell lying one arm deltoid rear": "liggende énarms bakre skulder med håndvekt",
  "dumbbell lying one arm press": "liggende énarms press med håndvekt",
  "dumbbell lying rear delt row": "liggende bakre skulder roing med håndvekt",
  "dumbbell lying rear lateral raise": "liggende bakre lateral heving med håndvekt",
  "dumbbell lying supine biceps curl": "liggende bicepscurl med håndvekt",
  "dumbbell neutral grip bench press": "benkpress med nøytralt grep",
  "dumbbell one arm bench fly": "énarms brystfly på benk med håndvekt",
  "dumbbell one arm chest fly on exercise ball": "énarms brystfly på treningsball",
  "dumbbell one arm concentration curl (on stability ball)": "énarms konsentrasjonskurl på treningsball",
  "dumbbell one arm decline chest press": "énarms negativ brystpress med håndvekt",
  "dumbbell one arm fly on exercise ball": "énarms fly på treningsball med håndvekt",
  "dumbbell one arm hammer preacher curl": "énarms hammergrep predikantcurl med håndvekt",
  "dumbbell one arm hammer press on exercise ball": "énarms hammergrep press på treningsball",
  "dumbbell one arm incline chest press": "énarms skrå brystpress med håndvekt",
  "dumbbell one arm kickback": "énarms kickback med håndvekt",
  "dumbbell one arm lateral raise": "énarms sideheving med håndvekt",
  "dumbbell one arm shoulder press": "énarms skulderpress med håndvekt",
  "dumbbell one arm standing curl": "énarms stående curl med håndvekt",
  "dumbbell one arm standing hammer curl": "énarms stående hammergrep curl",
  "dumbbell one arm upright row": "énarms oppreist roing med håndvekt",
  "dumbbell one leg fly on exercise ball": "ettbeins fly på treningsball med håndvekt",
  "dumbbell palm rotational bent over row": "roterende foroverlent roing med håndvekt",
  "dumbbell preacher curl over exercise ball": "predikantcurl over treningsball med håndvekt",
  "dumbbell press on exercise ball": "press på treningsball med håndvekt",
  "dumbbell prone incline curl": "skrå liggende curl med håndvekt",
  "dumbbell prone incline hammer curl": "skrå liggende hammergrep curl",
  "dumbbell pullover on exercise ball": "pullover på treningsball",
  "dumbbell push press": "push press med håndvekt",
  "dumbbell raise": "heving med håndvekt",
  "dumbbell rear fly": "bakre fly med håndvekt",
  "dumbbell reverse bench press": "omvendt benkpress med håndvekt",
  "dumbbell reverse fly": "omvendt fly med håndvekt",
  "dumbbell reverse preacher curl": "omvendt predikantcurl med håndvekt",
  "dumbbell reverse spider curl": "omvendt edderkopp-curl med håndvekt",
  "dumbbell romanian deadlift": "rumensk markløft med håndvekt",
  "dumbbell scott press": "Scott press med håndvekt",
  "dumbbell seated bent arm lateral raise": "sittende sideheving med bøyde armer",
  "dumbbell seated bent over alternate kickback": "sittende foroverlent vekselvis kickback",
  "dumbbell seated bent over triceps extension": "sittende foroverlent tricepsstrekk",
  "dumbbell seated bicep curl": "sittende bicepscurl med håndvekt",
  "dumbbell seated calf raise": "sittende tåhev med håndvekt",
  "dumbbell seated hammer curl": "sittende hammergrep curl med håndvekt",
  "dumbbell seated inner biceps curl": "sittende indre bicepscurl med håndvekt",
  "dumbbell seated kickback": "sittende kickback med håndvekt",
  "dumbbell seated lateral raise": "sittende sideheving med håndvekt",
  "dumbbell seated preacher curl": "sittende predikantcurl med håndvekt",
  "dumbbell seated shoulder press": "sittende skulderpress med håndvekt",
  "dumbbell seated triceps extension": "sittende tricepsstrekk med håndvekt",
  "dumbbell side bend": "sidebøy med håndvekt",
  "dumbbell single arm overhead carry": "énarms overhead bæring med håndvekt",
  "dumbbell squat": "knebøy med håndvekt",
  "dumbbell standing alternate hammer curl and press": "stående vekselvis hammergrep curl og press",
  "dumbbell standing alternate overhead press": "stående vekselvis overhead press med håndvekt",
  "dumbbell standing calf raise": "stående tåhev med håndvekt",
  "dumbbell standing concentration curl": "stående konsentrasjonskurl med håndvekt",
  "dumbbell standing kickback": "stående kickback med håndvekt",
  "dumbbell standing overhead press": "stående overhead press med håndvekt",
  "dumbbell standing reverse curl": "stående omvendt curl med håndvekt",
  "dumbbell standing triceps extension": "stående tricepsstrekk med håndvekt",
  "dumbbell step-up lunge": "step-up utfall med håndvekt",
  "dumbbell stiff leg deadlift": "stivt bein markløft med håndvekt",
  "dumbbell straight arm pullover": "rett arm pullover med håndvekt",
  "dumbbell sumo pull through": "sumo pull-through med håndvekt",
  "dumbbell tate press": "Tate press med håndvekt",
  "dumbbell twisting bench press": "vridnings-benkpress med håndvekt",
  "dumbbell upright row": "oppreist roing med håndvekt",
  "dumbbell w-press": "W-press med håndvekt",
  "dumbbell waiter biceps curl": "kelner bicepscurl med håndvekt",
  "dumbbell zottman curl": "Zottman curl med håndvekt",
  "dumbbell zottman preacher curl": "Zottman predikantcurl med håndvekt",
};

// ---------------------------------------------------------------------------
// Translate a single name
// ---------------------------------------------------------------------------

function translate(name: string): string | null {
  const lower = name.toLowerCase().trim();
  if (DICTIONARY[lower]) return DICTIONARY[lower];
  return null;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) { console.error("DATABASE_URL not set"); process.exit(1); }

  const sql = neon(dbUrl);
  const db = drizzle({ client: sql, schema });

  const rows = await db
    .select({ id: schema.exercises.id, name: schema.exercises.name })
    .from(schema.exercises)
    .where(isNull(schema.exercises.nameNo));

  console.log(`${rows.length} exercises uten norsk navn`);

  let translated = 0;
  let skipped = 0;

  for (const row of rows) {
    const nameNo = translate(row.name);
    if (nameNo) {
      await db
        .update(schema.exercises)
        .set({ nameNo })
        .where(drizzleSql`${schema.exercises.id} = ${row.id}`);
      translated++;
    } else {
      skipped++;
    }
    if ((translated + skipped) % 100 === 0) {
      process.stdout.write(`\r${translated + skipped} / ${rows.length} — ${translated} oversatt, ${skipped} beholdt engelsk`);
    }
  }

  console.log(`\nFerdig. ${translated} norske navn, ${skipped} beholdt engelsk (vises med engelsk navn).`);
}

main().catch((err) => {
  console.error("[FATAL]", err);
  process.exit(1);
});
